version: '2'

networks:
  sont_network:
    external:
      name: nginxproxynetwork

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: soundtoll_es
    restart: always
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    networks:
      - sont_network
    volumes:
      - /data/docker/volumes/sont_data/:/usr/share/elasticsearch/data

  sont_db:
    image: mysql:5.7
    container_name: soundtoll_mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    volumes:
      - /data/docker/volumes/sont_db/_data/mysql:/var/lib/mysql
    networks:
      - sont_network

  sont:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: soundtoll_application
    restart: always
    environment:
      - VIRTUAL_HOST=soundtoll.sd.di.huc.knaw.nl
    links:
      - elastic
      - sont_db
    ports:
      - 8080:80
    networks:
      - sont_network